"""Add unique constraint to stock table

Revision ID: 9141bdbca17c
Revises: 6d654f1d2be7
Create Date: 2025-06-19 08:19:00.562668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9141bdbca17c'
down_revision = '6d654f1d2be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_unique_constraint('_product_sklad_size_uc', ['product_id', 'sklad', 'size'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint('_product_sklad_size_uc', type_='unique')

    # ### end Alembic commands ###
